services:
  mysql:
    image: mysql:8
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 20s
      retries: 10
    networks:
      - todo_network

  backend:
    build: ./backend
    container_name: todo_backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      BACKEND_PORT: ${BACKEND_PORT}
      CORS_ORIGIN: http://localhost:${FRONTEND_PORT} 
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todo_network

  frontend:
    build: ./frontend
    container_name: todo_frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - todo_network

volumes:
  mysql_data:

networks:
  todo_network:
    driver: bridge
